// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "email": "support@example.com"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin/login": {
            "post": {
                "description": "使用用户名密码登录获取JWT令牌",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认证"
                ],
                "summary": "管理员登录",
                "parameters": [
                    {
                        "description": "登录信息",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/api.LoginResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/api.Response"
                        }
                    }
                }
            }
        },
        "/admin/software": {
            "get": {
                "description": "分页获取软件列表",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "软件管理"
                ],
                "summary": "获取软件列表",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "每页数量",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/api.ListResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "post": {
                "description": "创建新的软件项目",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "软件管理"
                ],
                "summary": "创建软件",
                "parameters": [
                    {
                        "description": "软件信息",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.CreateSoftwareRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/model.Software"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/admin/software/{id}": {
            "get": {
                "description": "根据ID获取软件详细信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "软件管理"
                ],
                "summary": "获取软件详情",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "软件ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/model.Software"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "put": {
                "description": "更新软件信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "软件管理"
                ],
                "summary": "更新软件",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "软件ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "软件信息",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.UpdateSoftwareRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/model.Software"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "delete": {
                "description": "软删除软件",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "软件管理"
                ],
                "summary": "删除软件",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "软件ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.Response"
                        }
                    }
                }
            }
        },
        "/admin/stats/downloads": {
            "get": {
                "description": "获取下载统计数据",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用量统计"
                ],
                "summary": "获取下载统计",
                "parameters": [
                    {
                        "type": "string",
                        "description": "开始日期",
                        "name": "start_date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "结束日期",
                        "name": "end_date",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/service.StatsResponse"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/admin/stats/software/{id}/downloads": {
            "get": {
                "description": "获取指定软件的下载统计",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用量统计"
                ],
                "summary": "获取软件下载统计",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "软件ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "integer",
                                            "format": "int64"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/admin/versions": {
            "get": {
                "description": "分页获取版本列表",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "版本管理"
                ],
                "summary": "获取版本列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "软件ID",
                        "name": "software_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "每页数量",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/api.ListResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "post": {
                "description": "创建新的软件版本",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "版本管理"
                ],
                "summary": "创建版本",
                "parameters": [
                    {
                        "description": "版本信息",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.CreateVersionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/model.Version"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/admin/versions/{id}": {
            "get": {
                "description": "根据ID获取版本详细信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "版本管理"
                ],
                "summary": "获取版本详情",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "版本ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/model.Version"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "put": {
                "description": "更新版本信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "版本管理"
                ],
                "summary": "更新版本",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "版本ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "版本信息",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.UpdateVersionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/model.Version"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "delete": {
                "description": "删除版本及其包文件",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "版本管理"
                ],
                "summary": "删除版本",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "版本ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.Response"
                        }
                    }
                }
            }
        },
        "/admin/versions/{id}/publish": {
            "post": {
                "description": "将版本状态改为已发布",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "版本管理"
                ],
                "summary": "发布版本",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "版本ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/model.Version"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/admin/versions/{id}/upload": {
            "post": {
                "description": "上传版本安装包",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "版本管理"
                ],
                "summary": "上传版本包",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "版本ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "安装包文件",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/model.Version"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/tenants": {
            "get": {
                "description": "分页获取租户列表（多租户预留）",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "租户管理"
                ],
                "summary": "获取租户列表",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "每页数量",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/api.ListResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "post": {
                "description": "创建新的租户（多租户预留）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "租户管理"
                ],
                "summary": "创建租户",
                "parameters": [
                    {
                        "description": "租户信息",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.CreateTenantRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/api.TenantResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/tenants/{id}": {
            "get": {
                "description": "根据ID获取租户详细信息（多租户预留）",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "租户管理"
                ],
                "summary": "获取租户详情",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "租户ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/model.Tenant"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "put": {
                "description": "更新租户信息（多租户预留）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "租户管理"
                ],
                "summary": "更新租户",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "租户ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "租户信息",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.UpdateTenantRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/model.Tenant"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "delete": {
                "description": "删除租户（多租户预留）",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "租户管理"
                ],
                "summary": "删除租户",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "租户ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.Response"
                        }
                    }
                }
            }
        },
        "/tenants/{id}/reset-key": {
            "post": {
                "description": "重置租户的API Key（多租户预留）",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "租户管理"
                ],
                "summary": "重置API Key",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "租户ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object",
                                            "additionalProperties": {
                                                "type": "string"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/update/check": {
            "get": {
                "description": "客户端检查是否有新版本可用",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "升级服务"
                ],
                "summary": "检查更新",
                "parameters": [
                    {
                        "type": "string",
                        "description": "软件标识",
                        "name": "software_slug",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "当前版本号",
                        "name": "current_version",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "平台",
                        "name": "platform",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "设备ID",
                        "name": "device_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "API密钥",
                        "name": "api_key",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/service.CheckUpdateResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.Response"
                        }
                    }
                }
            }
        },
        "/update/download/{id}": {
            "get": {
                "description": "下载指定版本的安装包",
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "升级服务"
                ],
                "summary": "下载版本包",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "版本ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "API密钥",
                        "name": "api_key",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.Response"
                        }
                    }
                }
            }
        },
        "/update/download/{id}/direct": {
            "get": {
                "description": "通过服务器中转下载安装包",
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "升级服务"
                ],
                "summary": "直接下载版本包",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "版本ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "API密钥",
                        "name": "api_key",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.Response"
                        }
                    }
                }
            }
        },
        "/update/latest": {
            "get": {
                "description": "获取软件的最新发布版本信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "升级服务"
                ],
                "summary": "获取最新版本",
                "parameters": [
                    {
                        "type": "string",
                        "description": "软件标识",
                        "name": "software_slug",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/model.Version"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.CreateTenantRequest": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "name": {
                    "type": "string"
                }
            }
        },
        "api.ListResponse": {
            "type": "object",
            "properties": {
                "list": {},
                "page": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "api.LoginRequest": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "api.LoginResponse": {
            "type": "object",
            "properties": {
                "expires_in": {
                    "type": "integer"
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "api.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "msg": {
                    "type": "string"
                }
            }
        },
        "api.TenantResponse": {
            "type": "object",
            "properties": {
                "api_key": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "expired_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "api.UpdateTenantRequest": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                }
            }
        },
        "model.Software": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "platform": {
                    "type": "string"
                },
                "slug": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                },
                "tenant_id": {
                    "description": "多租户预留字段",
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                },
                "versions": {
                    "description": "关联",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Version"
                    }
                }
            }
        },
        "model.Tenant": {
            "type": "object",
            "properties": {
                "api_key": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "expired_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "model.Version": {
            "type": "object",
            "properties": {
                "changelog": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "is_forced": {
                    "type": "boolean"
                },
                "is_incremental": {
                    "type": "boolean"
                },
                "min_version": {
                    "type": "string"
                },
                "package_hash": {
                    "type": "string"
                },
                "package_size": {
                    "type": "integer"
                },
                "package_url": {
                    "type": "string"
                },
                "published_at": {
                    "type": "string"
                },
                "software": {
                    "description": "关联",
                    "allOf": [
                        {
                            "$ref": "#/definitions/model.Software"
                        }
                    ]
                },
                "software_id": {
                    "type": "integer"
                },
                "status": {
                    "type": "integer"
                },
                "tenant_id": {
                    "description": "多租户预留字段",
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                },
                "version_code": {
                    "type": "integer"
                }
            }
        },
        "service.CheckUpdateResponse": {
            "type": "object",
            "properties": {
                "changelog": {
                    "type": "string"
                },
                "download_url": {
                    "type": "string"
                },
                "has_update": {
                    "type": "boolean"
                },
                "is_forced": {
                    "type": "boolean"
                },
                "is_incremental": {
                    "type": "boolean"
                },
                "min_version": {
                    "type": "string"
                },
                "package_hash": {
                    "type": "string"
                },
                "package_size": {
                    "type": "integer"
                },
                "published_at": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                },
                "version_code": {
                    "type": "integer"
                }
            }
        },
        "service.CreateSoftwareRequest": {
            "type": "object",
            "required": [
                "name",
                "platform",
                "slug"
            ],
            "properties": {
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "platform": {
                    "description": "windows/macos/linux",
                    "type": "string"
                },
                "slug": {
                    "type": "string"
                },
                "tenant_id": {
                    "description": "多租户预留",
                    "type": "integer"
                }
            }
        },
        "service.CreateVersionRequest": {
            "type": "object",
            "required": [
                "software_id",
                "version"
            ],
            "properties": {
                "changelog": {
                    "type": "string"
                },
                "is_forced": {
                    "type": "boolean"
                },
                "is_incremental": {
                    "type": "boolean"
                },
                "min_version": {
                    "type": "string"
                },
                "software_id": {
                    "type": "integer"
                },
                "tenant_id": {
                    "type": "integer"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "service.StatsResponse": {
            "type": "object",
            "properties": {
                "date": {
                    "type": "string"
                },
                "download_count": {
                    "type": "integer"
                },
                "unique_devices": {
                    "type": "integer"
                }
            }
        },
        "service.UpdateSoftwareRequest": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "platform": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                }
            }
        },
        "service.UpdateVersionRequest": {
            "type": "object",
            "properties": {
                "changelog": {
                    "type": "string"
                },
                "is_forced": {
                    "type": "boolean"
                },
                "is_incremental": {
                    "type": "boolean"
                },
                "min_version": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Type \"Bearer\" followed by a space and JWT token.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "软件升级管理系统 API",
	Description:      "支持多租户、多存储后端的软件升级管理服务",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
